--MOHAMED LUQMAN HADI BIN MOHAMED SUHAIRI 2210855
--MUAZZAM
--MIRZA
--IRFAN FIRDAUS    
--SYAHIR

--resets all tables and sequences
DROP TABLE WASTE;
DROP TABLE REDEEM;
DROP TABLE POINTS;
DROP TABLE STUDENT;
DROP TABLE PRODUCTS;
DROP SEQUENCE "wasteIDSeq";
DROP SEQUENCE "redeemSeq";
DROP SEQUENCE "productSeq";

--table creation
CREATE TABLE STUDENT (
STUDENT_ID         INTEGER,
STUDENT_NAME     VARCHAR(100),
STUDENT_POINTS     INTEGER,
STUDENT_PICTURE     BLOB,
mimetype        VARCHAR2(50),
filename        VARCHAR2(100),
created_date    DATE,
PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE WASTE (
WASTE_ID         NUMBER(5),
WASTE_DATETIME  DATE DEFAULT SYSDATE NOT NULL,
WASTE_QTY       NUMBER,
WASTE_LOCATION  VARCHAR(40),
WASTE_TYPE      VARCHAR(40),
WASTE_PICTURE   BLOB,
STUDENT_ID      INTEGER,
mimetype        VARCHAR2(50),
filename        VARCHAR2(100),
created_date    DATE,
PRIMARY KEY (WASTE_ID)
);

CREATE TABLE PRODUCTS (
PRODUCTS_ID       INTEGER,
PRODUCTS_NAME     VARCHAR(40),
PRODUCTS_QTY      INTEGER,
PRODUCTS_POINTS   INTEGER,
PRODUCTS_PICTURE  BLOB,
mimetype        VARCHAR2(50),
filename        VARCHAR2(100),
created_date    DATE,
PRIMARY KEY (PRODUCTS_ID)
);

CREATE TABLE REDEEM (
REDEEM_ID       INTEGER,
PRODUCTS_ID      INTEGER,
STUDENT_ID      INTEGER,
PRIMARY KEY (REDEEM_ID),
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
FOREIGN KEY (PRODUCTS_ID) REFERENCES PRODUCTS(PRODUCTS_ID)
);

CREATE TABLE POINTS (
STUDENT_ID       INTEGER,
POINTS_QTY       INTEGER,
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

--sequence declaration
CREATE SEQUENCE "wasteIDSeq"
MINVALUE 1
MAXVALUE 99999
INCREMENT BY 1
START WITH 1
CACHE 20
;
CREATE SEQUENCE "redeemSeq"
MINVALUE 1
MAXVALUE 99999
INCREMENT BY 1
START WITH 1
CACHE 20
;
CREATE SEQUENCE "productSeq"
MINVALUE 1
MAXVALUE 99999
INCREMENT BY 1
START WITH 1
CACHE 20
;

--TEST VALUES (15 as stated) (for student)
INSERT INTO STUDENT VALUES(2210855,'MOHAMED LUQMAN HADI BIN SUHAIRI',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2218867,'MIRZA DARWISY BIN MAHAZIR',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2214771,'MUHAMMAD SYAHIR BIN MOHD KAMAL',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2219361,'MUAZZAM HAZMI BIN SUKHAIMI',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2218453,'MOHAMAD IRFAN FIRDAUS BIN MOHD BASRI',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2210856,'MOHAMAD LUQMAN HAKIM BIN SUHAILI',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2218868,'MIRZU DARWISH BIN MAHADIR',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2214772,'AHMAD SYAH BIN ABDUL KAMAL',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2219362,'ZAM ZAHMIL BIN SUHAIMI',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2218454,'AHMEDIAH ARFANIAH DAULAN BINTI AHMAD BASRAN',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2210866,'AHMAD LUKMAN HAFIZ BIN SUHAILAN',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2218878,'MIRZAN DAHLAN BIN MAHADTIR',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2214782,'AHMADIAH SYAHDIAH BIN ABDULLAH KAMAL',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2219392,'ZAHMAD ZAHMIL BIN AHMAD SUHAILAN',0,null,null,null,null);
INSERT INTO STUDENT VALUES(2218484,'NUR IRFANIAH DAUS BINTI MOHD BASRAN',0,null,null,null,null);

COMMIT;​
