--MOHAMED LUQMAN HADI BIN MOHAMED SUHAIRI 2210855
--MUAZZAM
--MIRZA
--IRFAN FIRDAUS
--SYAHIR
-- semoga banger

--resets all tables
DROP TABLE STUDENT; 
DROP TABLE WASTE;
DROP TABLE REDEEM;
DROP TABLE POINTS;
DROP TABLE PRODUCT;

CREATE TABLE STUDENT (
STUDENT_ID 		INTEGER     NOT NULL,
STUDENT_NAME 	VARCHAR(35) NOT NULL,
STUDENT_POINTS 	INTEGER,
PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE WASTE (
WASTE_ID 	    INTEGER,
WASTE_DATETIME  DATE,
WASTE_LOCATION  VARCHAR(35),
WASTE_TYPE      VARCHAR(35),
STUDENT_ID      INTEGER,
PRIMARY KEY (WASTE_ID)
CONSTRAINT (WASTE_STUDENT_ID_FK)
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE PRODUCT (
PRODUCT_ID       INTEGER,
PRODUCT_NAME     VARCHAR(35),
PRODUCT_QTY      INTEGER,
PRODUCT_POINTS   INTEGER,
PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE REDEEM (
REDEEM_ID       INTEGER,
PRODUCT_ID      INTEGER,
STUDENT_ID      INTEGER,
PRIMARY KEY (WASTE_ID)
CONSTRAINT (REDEEM_STUDENT_ID_FK)
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID)
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE POINTS (
STUDENT_ID       INTEGER,
POINTS_QTY       INTEGER,
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID)
);

--TEST VALUES

INSERT INTO STUDENT VALUES(2210855,'Luqman Hadi',0);

COMMIT;